config/routes.rb
Rails.application.routes.draw do
  # verb path, to: "controllers#action"
  root to: "pages#home"
  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end

  def contact
    @members = %w(Eric Miklos Mathilde Linda)

    if params[:filter]
      @members.select! { |member|
        member.include?(params[:filter])
      }
    end
  end

  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    Navbar
    <%= yield %>
    <!-- <a href="/">Home</a>
    <a href="/contact">Contact</a>
    <a href="/about">About</a> -->
    <%= link_to "Home", root_path %>
    <%= link_to "Contact", contact_path %>
    <%= link_to "About", about_path %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/contact.html.erb
<h1>Contact</h1>


<form action="/contact" method="get">
  <input type="text" name="filter" placeholder="WHo are you looking for?" value='<%= params[:filter] %>'>
  <input type="submit">

</form>


<ol>
  <% @members.each do |member| %>
    <li>
      <%= member %>
    </li>
  <% end %>
</ol>

app/views/pages/home.html.erb
<h1>Welcome!</h1>
<p>Now is <%= Time.now %><p>